# Generated by Django 5.0.4 on 2024-10-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assetManagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="usageMinutes",
            field=models.IntegerField(default=0),
        ),
    ]
