# Generated by Django 5.0.4 on 2024-10-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assetOperation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="usageHours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="usageMinutes",
            field=models.IntegerField(default=0),
        ),
    ]
